apiVersion: v1
kind: Secret
metadata:
  name: openedx-external-services
  namespace: openedx
type: Opaque
stringData:
  MYSQL_HOST: "REPLACE_RDS_ENDPOINT"
  MYSQL_PORT: "3306"
  MYSQL_DB: "openedx"
  MYSQL_USER: "openedx_admin"
  MYSQL_PASSWORD: "REPLACE_ME"
  MONGO_HOST: "REPLACE_MONGO_HOST"
  MONGO_PORT: "27017"
  MONGO_USER: "openedx"
  MONGO_PASSWORD: "REPLACE_ME"
  ELASTICSEARCH_HOST: "REPLACE_OPENSEARCH_ENDPOINT"
  ELASTICSEARCH_PORT: "443"
  ELASTICSEARCH_SCHEME: "https"
  REDIS_HOST: "REPLACE_REDIS_ENDPOINT"
  REDIS_PORT: "6379"
